MODEL:
  LOAD_CHECKPOINT: False
  FREEZE: False
  CHECKPOINT: graphmodel/pre_label_demo01/fold2/epoch42_val_loss_1.9121_val_acc0.4385.pth
  GAT:
    IN_FEATS: 300
    HIDDEN_DIM: 32
    N_LAYERS: 2
    HEADS: [16, 16]
    FEAT_DROP: 0.6
    ATTN_DROP: 0.6
    LABEL_EMB: True
    LABEL_DROP: 0.5
    N_CLASS: 23
  GCN:
    IN_FEATS: 300
    OUT_FEATS: 512
    N_LAYERS: 2
    FEAT_DROP: 0.5
    LABEL_EMB: True
    LABEL_DROP: 0.5
    N_CLASS: 23

TRAIN:
  EPOCHS: 500
  LOG_STEP: 50
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0000001
  SEED: 2021
  OUT_PATH: graphmodel/
  NAME: pre_label_demo03
DATASET:
  DATA_PATH: ../data/
  NORM_FEATURE: False
  BATCH_SIZE: 512
  FANOUTS: [10, 20]
  NUM_WORKERS: 8
  N_CLASS: 23
  TEST_RESULT: test_result/dir_pre_result.csv