MODEL:
  GNN_MODEL: unicmp
  INPUT_SIZE: 300
  NUM_LAYERS: 2
  NUM_HEADS: 4
  HIDDEN_SIZE: 512
  NUM_CLASS: 23
  LABEL_DROP: 0.1
  FEAT_DORP: 0.0
  ATTN_DROP: 0.0
  DROP: 0.2
  USE_SAGE: True
  USE_CONV: True
  USE_ATTN: True
  USE_RESNET: True
  USE_DESNET: True
  SMOOTHING: 0.1
  CHECKPOINT: ''


DATASET:
  DATA_PATH: ../dataset
  SEED: 2021
  BATCH_SIZE: 1024
  LOG_STEP: 300
  FANOUTS: [30, 30]
  NUM_WORKERS: 2
  EPOCHS: 50
  LEARNING_RATE: 0.0003
  COEF_LR: 1.0
  WEIGHT_DECAY: 0.0001
  WARMUP_PROPORTION: 0.1
  GRADIENT_ACCUMULATION_STEPS: 1
  NORM_FEATURE: False
  OUT_PATH: ../results/unicmp_base
  MODEL_PREFIX: unicmp_base
  TEST_PREFIX: unimp_base
