MODEL:
  GNN_MODEL: unicmp
  INPUT_SIZE: 300
  NUM_LAYERS: 3
  NUM_HEADS: 8
  HIDDEN_SIZE: 512
  NUM_CLASS: 23
  LABEL_DROP: 0.1
  FEAT_DORP: 0.05
  GRAPH_DORP: 0.0
  ATTN_DROP: 0.0
  DROP: 0.2
  USE_SAGE: True
  USE_CONV: False
  USE_ATTN: False
  USE_RESNET: True
  USE_DESNET: True
  CHECKPOINT: ''


OPTIMIZER:
  LEARNING_RATE: 0.0005
  COEF_LR: 1.0
  SCHEDULE: warmup_linear
  WEIGHT_DECAY: 0.0001
  WARMUP_PROPORTION: 0.1


CRITERION:
  LOSS_TYPE: ASL
  NUM_CLASS: 23
  GAMMA_NEG: 4
  GAMMA_POS: 1
  SMOOTHING: 0.1


DATASET:
  SEED: 2021
  DATA_PATH: ../dataset
  EPOCHS: 30
  BATCH_SIZE: 512
  LOG_STEP: 600
  FANOUTS: [30, 20, 10]
  NUM_CLASS: 23
  REPLACE_LABEL: 0.04
  MASK_LABEL: 0.16
  EDGE_DROP: 0.2
  NUM_WORKERS: 2
  GRADIENT_ACCUMULATION_STEPS: 1
  NORM_FEATURE: False
  OUT_PATH: ../models/unicmp
  MODEL_PREFIX: unicmp
  TEST_PREFIX: unicmp
