MODEL:
  GNN_MODEL: unicmp
  INPUT_SIZE: 300
  NUM_LAYERS: 2
  NUM_HEADS: 8
  HIDDEN_SIZE: 512
  NUM_CLASS: 23
  LABEL_DROP: 0.1
  FEAT_DORP: 0.0
  ATTN_DROP: 0.0
  DROP: 0.2
  USE_SAGE: True
  USE_CONV: True
  USE_ATTN: True
  USE_RESNET: True
  USE_DESNET: True
  CHECKPOINT: ''


OPTIMIZER:
  LEARNING_RATE: 0.0003
  COEF_LR: 1.0
  SCHEDULE: warmup_linear
  WEIGHT_DECAY: 0.0001
  WARMUP_PROPORTION: 0.1


CRITERION:
  LOSS_TYPE: ASL
  NUM_CLASS: 23
  GAMMA_NEG: 4
  GAMMA_POS: 1
  SMOOTHING: 0.1


DATASET:
  SEED: 2021
  DATA_PATH: ../dataset/split1
  EPOCHS: 50
  BATCH_SIZE: 1024
  LOG_STEP: 300
  FANOUTS: [30, 30]
  NUM_CLASS: 23
  REPLACE_LABEL: 0.06
  MASK_LABEL: 0.24
  EDGE_DROP: 0.2
  NUM_WORKERS: 2
  GRADIENT_ACCUMULATION_STEPS: 1
  NORM_FEATURE: False
  OUT_PATH: ../models/unicmp_split1
  MODEL_PREFIX: unicmp_split1
  TEST_PREFIX: unicmp_split1
