MODEL:
  GNN_MODEL: unicmp # ['graphsage', 'graphconv', 'graphattn', 'graphmodel', 'unimp', 'unimpplus']
  MODE: 1
  IN_FEAT: 300
  HIDDEN_DIM: 512
  N_LAYERS: 2
  MLP_DIM: 256
  NUM_HEADS: 8
  N_CLASS: 23
  INPUT_DROP: 0.1
  DROP_RATE: 0.2
  ATTN_DROP: 0.
  GRAPH_DORP: 0.
  LABEL_DROP: 0.25
  FEAT_DORP: 0.
  USE_SAGE: False
  USE_CONV: False
  USE_ATTN: True
  USE_RESNET: True
  USE_DESNET: True
  CHECKPOINT: graphmodel/split2/norm_lstm_unicmp_dgl_model_epoch21_valloss_1.2181_val_0.6263.pth
  CHECKPOINTS: [graphmodel/split0/lstm_768_unicmp_dgl_model_epoch13_valloss_1.2166_val_0.6262.pth, graphmodel/split1/lstm_768_unicmp_dgl_model_epoch12_valloss_1.2190_val_0.6216.pth, graphmodel/split2/lstm_768_unicmp_dgl_model_epoch12_valloss_1.2126_val_0.6252.pth, graphmodel/split3/lstm_768_unicmp_dgl_model_epoch15_valloss_1.2315_val_0.6213.pth]

DATASET:
  DATA_PATH: ../data/
  BATCH_SIZE: 512
  EPOCHS: 30
  LEARNING_RATE: 0.0001
  COEF_LR: 0.8
  WEIGHT_DECAY: 0.0001  #0.0005
  WARMUP_PROPORTION: 0.1
  GRADIENT_ACCUMULATION_STEPS: 1
  SEED: 2021
  NUM_WORKERS: 2
  LOG_STEP: 500
  FANOUTS: [30, 30] #[30, 20, 10]
  NORM_FEATURE: False
  K_FOLD: 2 #[0, 1, 2, 3, 4]
  OUT_PATH: graphmodel/split
  TEST_RESULT: test_result/split2_norm_lstm_unicmp_dgl_model_epoch21_valloss_1.2181_val_0.6263_result.csv
  K_FOLD_PATH: test_result/se_lstm768_unicmp_k_fold_4.csv