MODEL:
  GNN_MODEL: unimp
  INPUT_SIZE: 300
  FEAT_SIZE: 738
  NUM_CLASS: 23
  NUM_LAYERS: 2
  NUM_HEADS: 8
  HIDDEN_SIZE: 512
  ATTN_HEADS: 8
  LABEL_DROP: 0.1
  FEAT_DORP: 0.05
  GRAPH_DORP: 0.0
  ATTN_DROP: 0.0
  DROP: 0.2
  USE_SAGE: True
  USE_CONV: False
  USE_ATTN: True
  USE_RESNET: True
  USE_DESNET: True
  USE_SEMUL: True
  GATV2: False
  CHECKPOINT: ''
  CHECKPOINT_BASE: ../dgl_models/order_deepwalk2_gat1_se
  CHECKPOINT_LIST: ['split4/models/unimp_epoch01_val5953.pth']

OPTIMIZER:
  LEARNING_RATE: 0.0005
  COEF_LR: 1.0
  SCHEDULE: warmup_linear
  WEIGHT_DECAY: 0.0001
  WARMUP_PROPORTION: 0.1


CRITERION:
  LOSS_TYPE: CL
  NUM_CLASS: 23
  GAMMA_NEG: 4
  GAMMA_POS: 1
  SMOOTHING: 0.1


DATASET:
  SEED: 2021
  K_FOLD: -1
  GRAPH_PATH: ../final_dataset/graph.bin
  LABEL_PATH: ../final_dataset/order_labels/label_split
  NODE_PATH: ../final_dataset/features.npy
  WALK_PATH: ../final_dataset/deep_walk2.npy
  EDGE_PATH: ../final_dataset/features_neigh.npy
  EPOCHS: 50
  BATCH_SIZE: 1024
  LOG_STEP: 200
  FANOUTS: [30, 30]
  NUM_CLASS: 23
  REPLACE_LABEL: 0.04
  MASK_LABEL: 0.16
  EDGE_DROP: 0.2
  NUM_WORKERS: 2
  GRADIENT_ACCUMULATION_STEPS: 1
  OUT_PATH: ../dgl_models/final/order_deepwalk2_gat1_se
  MODEL_PREFIX: models
  TEST_PREFIX: order_deepwalk2_gat1_se
