MODEL:
  GNN_MODEL: unicmp
  INPUT_SIZE: 300
  NUM_LAYERS: 2
  NUM_HEADS: 8
  HIDDEN_SIZE: 512
  NUM_CLASS: 23
  LABEL_DROP: 0.1
  FEAT_DORP: 0.05
  GRAPH_DORP: 0.0
  ATTN_DROP: 0.0
  DROP: 0.2
  USE_SAGE: True
  USE_CONV: False
  USE_ATTN: True
  USE_RESNET: True
  USE_DESNET: True
  CHECKPOINT: ''


OPTIMIZER:
  LEARNING_RATE: 0.0005
  COEF_LR: 1.0
  SCHEDULE: warmup_linear
  WEIGHT_DECAY: 0.0001
  WARMUP_PROPORTION: 0.1


CRITERION:
  LOSS_TYPE: CL
  NUM_CLASS: 23
  GAMMA_NEG: 4
  GAMMA_POS: 1
  SMOOTHING: 0.1


DATASET:
  SEED: 2021
  DATA_PATH: ../dataset
  K_FOLD: 2 #[0, 1, 2, 3, 4]
  EPOCHS: 50
  BATCH_SIZE: 2048
  LOG_STEP: 200
  FANOUTS: [30, 30]
  IN_FANOUTS: [25, 25]
  OUT_FANOUTS: [25, 25]
  NUM_CLASS: 23
  REPLACE_LABEL: 0.04
  MASK_LABEL: 0.16
  EDGE_DROP: 0.2
  NUM_WORKERS: 2
  GRADIENT_ACCUMULATION_STEPS: 1
  NORM_FEATURE: False
  OUT_PATH: ../dgl_model/dunicmp/unicmp_split2
  MODEL_PREFIX: unicmp_split2
  TEST_PREFIX: unicmp_split2
